### ISSUE TITLE
MongoDB not connecting properly

### ISSUE THREAD

**Issue by XDRmc** [Elb1to/SoupPvP#29]
this also makes it so people can't join the server.

when server starting:

```
[09:50:16 INFO]: [SoupPvP] Enabling SoupPvP v1.0-SNAPSHOT
[09:50:16 INFO]: ------------------------------------------------
[09:50:16 INFO]: SoupPvP - Lunar.GG Replica - v1.0-SNAPSHOT
[09:50:16 INFO]: Made on Frozed Club Development by Elb1to
[09:50:16 INFO]: ------------------------------------------------
[09:50:16 WARN]: [Server thread] INFO org.mongodb.driver.cluster - Cluster created with settings {hosts=[rs0/n1-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017,n2-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
[09:50:16 WARN]: [cluster-ClusterId{value='62dbb648af22586513bc889f', description='null'}-rs0/n1-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017,n2-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017:27017] INFO org.mongodb.driver.cluster - Exception in monitor thread while connecting to server rs0/n1-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017,n2-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017:27017
[09:50:16 WARN]: com.mongodb.MongoSocketException: rs0/n1-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017,n2-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017
[09:50:16 WARN]:        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:211)
[09:50:16 WARN]:        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:75)
[09:50:16 WARN]:        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65)
[09:50:16 WARN]:        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126)
[09:50:16 WARN]:        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117)
[09:50:16 WARN]:        at java.lang.Thread.run(Unknown Source)
[09:50:16 WARN]: Caused by: java.net.UnknownHostException: rs0/n1-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017,n2-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017
[09:50:16 WARN]:        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[09:50:16 WARN]:        at java.net.InetAddress$2.lookupAllHostAddr(Unknown Source)
[09:50:16 WARN]:        at java.net.InetAddress.getAddressesFromNameService(Unknown Source)
[09:50:16 WARN]:        at java.net.InetAddress.getAllByName0(Unknown Source)
[09:50:16 WARN]:        at java.net.InetAddress.getAllByName(Unknown Source)
[09:50:16 WARN]:        at java.net.InetAddress.getAllByName(Unknown Source)
[09:50:16 WARN]:        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:203)
[09:50:16 WARN]:        ... 5 more
```

When player joins:

```
[09:50:21 WARN]: [User Authenticator #1] INFO org.mongodb.driver.cluster - Cluster description not yet available. Waiting for 30000 ms before timing out
[09:50:51 INFO]: com.mojang.authlib.GameProfile@3fbc04e7[id=8e653a85-f09e-4427-a51e-654de45b34d4,name=XDRmc,properties={textures=[com.mojang.authlib.properties.Property@4d1efea9]},legacy=false] (/127.0.0.1:52354) lost connection: Disconnected
[09:50:51 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to SoupPvP v1.0-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[server.jar:]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[server.jar:]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[server.jar:]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:276) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.LoginListener.lambda$a$2(LoginListener.java:229) ~[server.jar:]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_331]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_331]
        at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_331]
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=rs0/n1-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017,n2-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: rs0/n1-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017,n2-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017}, caused by {java.net.UnknownHostException: rs0/n1-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017,n2-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017}}]
        at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:182) ~[?:?]
        at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41) ~[?:?]
        at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136) ~[?:?]
        at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94) ~[?:?]
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249) ~[?:?]
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172) ~[?:?]
        at com.mongodb.client.internal.FindIterableImpl.first(FindIterableImpl.java:199) ~[?:?]
        at me.elb1to.souppvp.user.UserManager.loadUser(UserManager.java:34) ~[?:?]
        at me.elb1to.souppvp.user.User.<init>(User.java:40) ~[?:?]
        at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_331]
        at me.elb1to.souppvp.user.UserManager.getOrCreate(UserManager.java:22) ~[?:?]
        at me.elb1to.souppvp.listeners.UserListener.onAsyncPlayerPreLogin(UserListener.java:35) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_331]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_331]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_331]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_331]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:]
        ... 9 more
```

**Comment by Elb1to** [comment]
That's an issue from your Mongo, not the plugin.
